import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import { spawnSync } from 'node:child_process';
const bin=path.resolve('bin/eutrya.mjs');
function rig(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'eutrya-cli2-')),config=path.join(root,'config.json');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const env={...process.env,EUTRYA_CONFIG_HOME:root,AI_GATEWAY_API_KEY:'',OPENROUTER_API_KEY:''};const run=(...args)=>spawnSync(process.execPath,[bin,...args,'--config',config,'--cwd',root],{env,encoding:'utf8',timeout:12000});return {root,config,run,env};}
test('setup creates distinct OpenRouter and Vercel configuration without storing credentials',t=>{const {root,config,run}=rig(t);const r=run('setup','--provider','openrouter','--model','fixture/model','--data-root',path.join(root,'data'),'--session-root',path.join(root,'sessions'));assert.equal(r.status,0,r.stdout+r.stderr);const c=JSON.parse(fs.readFileSync(config));assert.equal(c.mainProvider,'openrouter');assert.equal(c.jevModel,'typesafe-ai/jev');assert.ok(!fs.existsSync(path.join(root,'.env')));assert.notEqual(run('setup','--model','other/model').status,0);});
test('gateway CLI creates explicit sender allowlists without contacting platforms',t=>{const {root,run}=rig(t);let r=run('gateway','setup','--platform','telegram','--user','12345');assert.equal(r.status,0,r.stdout+r.stderr);const c=JSON.parse(fs.readFileSync(path.join(root,'gateway.json')));assert.equal(c.platforms.telegram.enabled,true);assert.deepEqual(c.platforms.telegram.allowedUsers,['12345']);assert.equal(c.allowExec,false);assert.notEqual(run('gateway','setup','--platform','telegram','--user','*').status,0);});
test('CLI memory and skills persist, remain reviewable and show exact contents',t=>{const {root,run}=rig(t),data=path.join(root,'data');assert.equal(run('memory','add','prefer verified observations','--data-root',data).status,0);assert.match(run('memory','list','--data-root',data).stdout,/verified observations/);const kp=run('memory','path','--data-root',data).stdout.trim();assert.ok(path.isAbsolute(kp));assert.ok(fs.existsSync(path.join(kp,'memory.json')));assert.equal(run('skills','path','--data-root',data).stdout.trim(),kp);const file=path.join(root,'SKILL.md');fs.writeFileSync(file,'---\nname: fixture\ndescription: Test reference\n---\nVerify outputs.');assert.equal(run('skills','install','fixture',file,'--data-root',data).status,0);assert.match(run('skills','list','--data-root',data).stdout,/fixture/);});
test('CLI jobs accept IANA timezone and a bounded local task',t=>{const {root,run}=rig(t),data=path.join(root,'data');const r=run('jobs','add','--task','review local notes','--cron','0 9 * * *','--timezone','America/Phoenix','--data-root',data);assert.equal(r.status,0,r.stdout+r.stderr);const rows=JSON.parse(run('jobs','list','--data-root',data).stdout);assert.equal(rows[0].timezone,'America/Phoenix');assert.equal(rows[0].allowWrite,false);});
test('CLI MCP template is disabled and does not auto-start an untrusted executable',t=>{const {root,run}=rig(t);assert.equal(run('mcp','init').status,0);const c=JSON.parse(fs.readFileSync(path.join(root,'mcp.json')));assert.equal(c.servers.example.enabled,false);assert.equal(c.servers.example.trusted,false);assert.match(run('mcp','list').stdout,/No external server was started/);});
test('CLI doctor distinguishes missing SDK from a live provider check',t=>{const {run}=rig(t);const r=run('doctor');assert.equal(r.status,0);assert.match(r.stdout,/"liveTest": "NOT RUN"/);assert.match(r.stdout,/"nousServices": false/);assert.notEqual(run('doctor','--live').status,0);});
test('demo still verifies independently, and exported trace contains mandatory decisions',t=>{const {root,run}=rig(t),sessionRoot=path.join(root,'sessions');const r=run('demo','--session-root',sessionRoot);assert.equal(r.status,0,r.stdout+r.stderr);assert.match(r.stdout,/VERIFIED/);const out=path.join(root,'export.json'),ex=run('export','latest','--output',out,'--session-root',sessionRoot);assert.equal(ex.status,0,ex.stdout+ex.stderr);assert.ok(JSON.parse(fs.readFileSync(out)).events.some(e=>e.type==='jev.control'));assert.notEqual(run('export','latest','--output',out,'--session-root',sessionRoot).status,0);});
