import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import { Jobs,Scheduler,parseCron,cronMatches,runJob,runTeam } from '../src/scheduler.mjs';
import { DEFAULTS } from '../src/config.mjs';import { McpTools } from '../src/mcp.mjs';
import { makeEngine } from '../src/bootstrap.mjs';import { Store } from '../src/store.mjs';
import { ScriptedCortex } from '../src/providers/mock.mjs';import { proposal } from './helpers.mjs';
const tmp=t=>{const r=fs.mkdtempSync(path.join(os.tmpdir(),'eutrya-jobs-'));t.after(()=>fs.rmSync(r,{recursive:true,force:true}));return r;};
const config=root=>({...DEFAULTS,dataRoot:path.join(root,'data'),sessionRoot:path.join(root,'sessions'),maxSteps:2,retries:0});
test('cron supports numeric ranges, lists and steps',()=>{const c=parseCron('*/15 8-10 * * 1,3,5');assert.equal(c[0].values.has(30),true);assert.equal(c[1].values.has(11),false);assert.equal(c[4].values.has(3),true);});
test('cron validates ranges and number of fields',()=>{for(const c of ['* * *','61 * * * *','0 24 * * *','*/0 * * * *','@hourly','0 9 * * MON'])assert.throws(()=>parseCron(c));});
test('cron is timezone-aware rather than using the machine timezone',()=>{assert.equal(cronMatches('0 9 * * *',new Date('2026-09-17T16:00:00Z'),'America/Phoenix'),true);assert.equal(cronMatches('0 9 * * *',new Date('2026-09-17T16:00:00Z'),'UTC'),false);});
test('cron combines restricted day-of-month and weekday with OR',()=>{assert.equal(cronMatches('0 9 1 * 4',new Date('2026-09-17T09:00:00Z')),true);assert.equal(cronMatches('0 9 1 * 1',new Date('2026-09-17T09:00:00Z')),false);});
test('one-shot schedule requires an explicit timezone and future date',t=>{const root=tmp(t),j=new Jobs(root);assert.throws(()=>j.add({task:'x',workspace:root,at:'2099-01-01T09:00:00'}),/offset/);assert.throws(()=>j.add({task:'x',workspace:root,at:'2001-01-01T09:00:00Z'}),/future/);});
test('scheduler durably claims before execution and does not repeat the same minute',async t=>{const root=tmp(t),j=new Jobs(root);j.add({task:'fixture',workspace:root,cron:'* * * * *'});let calls=0;const s=new Scheduler(j,async()=>{calls++;assert.equal(j.list()[0].status,'running');return {status:'ANSWERED'};});const time=new Date('2026-09-17T10:00:00Z');await s.tick(time);await s.tick(time);assert.equal(calls,1);await s.tick(new Date('2026-09-17T10:01:00Z'));assert.equal(calls,2);});
test('interrupted scheduled work requires review and is never automatically replayed',async t=>{const root=tmp(t),j=new Jobs(root);j.add({task:'x',workspace:root,cron:'* * * * *'});j.db.transaction(s=>{s.jobs[0].status='running';});let calls=0;const s=new Scheduler(j,async()=>{calls++;});s.recover();await s.tick();assert.equal(j.list()[0].status,'needs_review');assert.equal(calls,0);});
test('stopped scheduler does not start queued due tasks',async t=>{const root=tmp(t),j=new Jobs(root);j.add({task:'x',workspace:root,cron:'* * * * *'});const c=new AbortController();c.abort();let calls=0;await new Scheduler(j,async()=>{calls++;},{signal:c.signal}).tick();assert.equal(calls,0);});
test('scheduled run uses Jev with no process tool and writes a result artifact',async t=>{const root=tmp(t),c=config(root);const result=await runJob({id:'fixture-job',workspace:root,task:'Hello scheduler',allowWrite:false,maxCalls:10,maxSteps:2},c,{demo:true});assert.equal(result.status,'ANSWERED');assert.equal(result.meter.jevCalls,2);assert.equal(fs.readdirSync(path.join(c.dataRoot,'job-results','fixture-job')).length,1);});
test('parallel team has one shared request cap, not a cap per child',async t=>{const root=tmp(t),c={...config(root),maxCalls:4};const report=await runTeam([{task:'One',workspace:root},{task:'Two',workspace:root}],c,{demo:true,parallel:2});assert.ok(report.calls<=4);assert.equal(report.results.length,2);assert.ok(report.results.some(r=>r.status!=='ANSWERED'));});
test('all team workspaces are validated before any child starts',async t=>{const root=tmp(t);await assert.rejects(()=>runTeam([{task:'valid',workspace:root},{task:'invalid',workspace:path.join(root,'missing')}],config(root),{demo:true}),/ENOENT/);assert.ok(!fs.existsSync(path.join(root,'data','teams')));});
function modules(){
 const observed={clients:[],transports:[],calls:[]};
 class Client{constructor(info,options){this.info=info;this.options=options;observed.clients.push(this);}async connect(t,opts){this.transport=t;}async listTools(){return {tools:[{name:'echo',description:'fixture tool',inputSchema:{type:'object',properties:{text:{type:'string'}},required:['text'],additionalProperties:false}},{name:'unlisted',inputSchema:{type:'object'}}]};}async callTool(a,_schema,options){observed.calls.push({a,options});return {content:[{type:'text',text:a.arguments.text}]};}async close(){this.closed=true;}}
 class Transport{constructor(...args){this.args=args;observed.transports.push(this);}}
 class AjvFixture{compile(){return x=>x&&typeof x==='object'&&typeof x.text==='string'&&Object.keys(x).length===1;}}
 return {observed,classes:{Client,StdioClientTransport:Transport,StreamableHTTPClientTransport:Transport,Ajv:AjvFixture}};
}
const server={enabled:true,trusted:true,transport:'stdio',command:'fixture-server',args:[],allowedTools:['echo'],passEnv:[]};
test('MCP starts only explicitly trusted servers and exact allowed tools',async()=>{const {classes}=modules();const bad=new McpTools({local:{...server,trusted:false}},{modules:classes});await assert.rejects(()=>bad.connect(),/trusted/);const m=new McpTools({local:server},{modules:classes});try{await m.connect();assert.deepEqual(m.catalog().map(t=>t.name),['echo']);assert.throws(()=>m.inspect({server:'local',tool:'unlisted',arguments:{}}),/explicitly enabled/);}finally{await m.close();}});
test('MCP child process receives only explicit environment credentials',async()=>{const {classes,observed}=modules();const m=new McpTools({local:{...server,passEnv:['SOME_SERVICE_TOKEN']}},{modules:classes,env:{PATH:'/bin',HOME:'/home/fixture',AI_GATEWAY_API_KEY:'not-passed',OPENROUTER_API_KEY:'not-passed',SOME_SERVICE_TOKEN:'operator-approved'}});try{await m.connect();const env=observed.transports[0].args[0].env;assert.equal(env.SOME_SERVICE_TOKEN,'operator-approved');assert.equal(env.AI_GATEWAY_API_KEY,undefined);assert.deepEqual(observed.clients[0].options.capabilities,{});}finally{await m.close();}});
test('MCP argument validation happens before external call',async()=>{const {classes,observed}=modules(),m=new McpTools({local:server},{modules:classes});try{await m.connect();await assert.rejects(()=>m.call({server:'local',tool:'echo',arguments:{text:123}}),/Schema/);assert.equal(observed.calls.length,0);await m.call({server:'local',tool:'echo',arguments:{text:'ok'}});assert.equal(observed.calls.length,1);}finally{await m.close();}});
test('MCP model action cannot execute without Jev and operator approval',async t=>{const root=tmp(t),c=config(root),store=new Store(c.sessionRoot,root),{classes,observed}=modules(),m=new McpTools({local:server},{modules:classes});await m.connect();t.after(async()=>{store.close();await m.close();});let approvals=0;const e=makeEngine({store,config:{...c,maxSteps:1},demo:true,mcp:m,approve:async()=>{approvals++;return false;}});e.cortex=new ScriptedCortex([proposal([{type:'mcp',server:'local',tool:'echo',arguments:{text:'ok'}}])]);e.startTask('Try fixture tool');await e.run();assert.equal(e.state.meter.jevCalls,2);assert.equal(approvals,1);assert.equal(observed.calls.length,0);});
