[package]
name = "eutrya-desktop"
version = "0.4.4"
description = "Eutrya native swarm desktop"
authors = ["Eutrya contributors"]
edition = "2021"

[lib]
name = "eutrya_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
