/* Small DOM-generating components. Images are decoration; labels/actions remain live HTML. */
(() => {
  const U=window.EutryaUI,{icon,logo}=U;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const PAGES=['dashboard','swarm','library','memory','tools','settings'];
  const title=p=>p.charAt(0).toUpperCase()+p.slice(1);
  const asset = file => './assets/' + file;
  const portrait=id=>asset(`agent-${({admin:'admin',engineer:'engineer',legal:'lawyer',lawyer:'lawyer',finance:'finance',researcher:'researcher'})[id]||'researcher'}.jpg`);
  const roleIcon=id=>({legal:'lawyer'})[id]||id;
  const num=n=>Number.isFinite(Number(n))?Number(n):0;
  const time=value=>{const d=new Date(value);return Number.isFinite(+d)?d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—'};
  const date=value=>{const d=new Date(value);return Number.isFinite(+d)?d.toLocaleDateString([],{month:'short',day:'numeric'}):'—'};
  const pill=(label,tone='neutral')=>`<span class="pill ${esc(tone)}">${esc(label)}</span>`;
  const status=s=>{const v=String(s||'offline').toLowerCase();return `<span class="status ${['online','idle','ready','live','enabled'].includes(v)?'ok':['working','thinking','reviewing','demo'].includes(v)?'blue':['blocked','error','offline','disabled'].includes(v)?'muted':'amber'}"><i></i>${esc(v)}</span>`};
  const button=(label,action='',options={})=>`<button class="btn ${options.primary?'primary':''} ${options.cls||''}" ${action?`data-action="${esc(action)}"`:''} ${options.attrs||''} ${options.disabled?'disabled':''}>${options.icon?icon(options.icon):''}<span>${esc(label)}</span></button>`;
  const miniButton=(label,action,name,attrs='')=>`<button class="icon-btn" title="${esc(label)}" aria-label="${esc(label)}" data-action="${esc(action)}" ${attrs}>${icon(name)}</button>`;
  const frame=(name,meta,content,cls='',actions='')=>`<section class="frame ${cls}"><header class="frame-heading"><h2>${esc(name)}</h2>${meta?`<span class="frame-meta">${esc(meta)}</span>`:''}<div class="frame-actions">${actions}</div></header>${content}</section>`;
  const empty=(heading,text,action='')=>`<div class="empty"><span class="empty-symbol">${icon('plus')}</span><strong>${esc(heading)}</strong><p>${esc(text)}</p>${action}</div>`;
  const field=(label,name,value,options={})=>`<label class="field"><span>${esc(label)}</span><input name="${esc(name)}" value="${esc(value)}" ${options.type?`type="${options.type}"`:''} ${options.attrs||''} ${options.placeholder?`placeholder="${esc(options.placeholder)}"`:''}>${options.help?`<small>${esc(options.help)}</small>`:''}</label>`;
  const select=(label,name,value,choices)=>`<label class="field"><span>${esc(label)}</span><select name="${esc(name)}">${choices.map(c=>{const [v,l]=Array.isArray(c)?c:[c,c];return `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`}).join('')}</select></label>`;
  const toggle=(label,help,name,checked)=>`<label class="toggle-row"><span><strong>${esc(label)}</strong><small>${esc(help)}</small></span><input class="switch" type="checkbox" name="${esc(name)}" ${checked?'checked':''}></label>`;
  const art=(cls='',variant='hero')=>`<svg class="botanical ${cls}" viewBox="${variant==='hero'?'945 145 465 650':'152 250 470 1050'}" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><image href="${asset(variant==='hero'?'dashboard-hero.jpg':'sidebar-botanical.jpg')}" width="${variant==='hero'?1672:941}" height="${variant==='hero'?941:1672}"/></svg>`;
  const descriptions={dashboard:['Eutrya','A durable mind for a more intelligent tomorrow.','A more capable you,\nfor a more interesting future.','PLAN · REASON · EXECUTE'],swarm:['Swarm','Many minds. A higher purpose.','Intelligence multiplies\nwhen minds work together.','COORDINATE · SYNTHESIZE · PROGRESS'],library:['Agent Library','Discover. Configure. Deploy.','Better questions\nbuild a brighter tomorrow.','SPECIALIZED MINDS · SHARED CONTEXT'],memory:['Memory','Capture. Connect. Reason. Evolve.','The more we remember,\nthe more we can become.','KNOWLEDGE GROWS · CONTEXT PERSISTS'],tools:['Tools','Build higher capabilities through intelligent tools.','Better tools\ncreate braver thinkers.','OBSERVE · REASON · ACT'],settings:['Settings','Configure today for a more intelligent tomorrow.','Better systems\nmake intelligence durable.','CONFIGURE · PROTECT · EVOLVE']};
  function hero(page,metrics=''){
    const [heading,sub,quote,steps]=descriptions[page];
    return `<section class="hero-group ${page==='dashboard'?'dashboard-hero':''}"><div class="hero-plate"><div class="registration" aria-hidden="true">+<br>■<br>■<br>✦<br>+<br>■</div>${art()}<div class="hero-copy"><p class="eyebrow">${page==='dashboard'?'NATIVE SWARM HARNESS':`${page.toUpperCase()} / EUTRYA`}</p><h1>${heading}</h1><p class="hero-subtitle">${sub}</p><div class="hero-folio"><span>${steps}</span><span>v0.2.0</span></div></div><span class="crosshair cross-one" aria-hidden="true"></span></div><div class="hero-aside"><div class="quote-plate">${art()}<span class="quote-mark">“</span><blockquote>${quote.replace('\n','<br>')}</blockquote><cite>— EUTRYA</cite></div>${metrics}</div></section>`;
  }
  function shell(){
    return `<div class="desktop-shell"><header class="titlebar" id="titlebar"><div class="traffic" aria-hidden="true"><i></i><i></i><i></i></div><div class="titlebar-copy">// ORCHESTRATE HIGHER INTELLIGENCE</div><div id="connection-label" class="connection-label">LOCAL · CONNECTING</div><div class="window-buttons">${miniButton('Minimize','window-min','minus')}${miniButton('Maximize / restore','window-max','maximize')}${miniButton('Close Eutrya','window-close','close')}</div></header><aside class="sidebar"><div class="brand">${logo()}<div><strong>Eutrya</strong><small>v0.2.0</small></div></div><nav aria-label="Main navigation">${PAGES.map(p=>`<button class="nav-link" data-page="${p}" title="${title(p)}" aria-label="${title(p)}">${icon(p)}<span>${title(p)}</span></button>`).join('')}</nav><div class="sidebar-art">${art('','sidebar')}</div><div class="sidebar-philosophy">HUMAN<br>AI<br>HIGHER<br>INTELLIGENCE<span>// eutrya<br>BUILT FOR<br>THE LONG RUN</span></div><div class="sidebar-bottom">${icon('lock')}<span>LOCAL WORKSPACE</span></div></aside><main id="main-scroll" class="main-scroll"><div id="page-content"></div><footer class="page-footer"><span>EUTRYA / <b id="footer-page">DASHBOARD</b></span><span>HUMAN × SWARM × POSSIBILITY</span><span>UI / 03</span></footer></main><div id="notice" class="notice" role="status" hidden></div><dialog id="ui-dialog" class="modal"></dialog><dialog id="approval-dialog" class="modal"></dialog></div>`;
  }
  function agentCard(a,selected=false,variant='profile'){
    return `<button class="agent-card ${variant} ${selected?'selected':''}" data-agent="${esc(a.id)}" aria-pressed="${selected}"><div class="agent-visual"><img src="${portrait(a.id)}" alt="" loading="lazy"><span class="agent-index">${esc(a.index)}</span><span class="agent-glyph">${icon(roleIcon(a.id))}</span></div><div class="agent-content"><h3>${esc(a.name)}</h3>${status(a.status)}<p>${esc(a.role)}</p><div class="tags">${(a.verbs||[]).slice(0,3).map(t=>pill(t)).join('')}</div><footer><span>JEV / ${num(a.tasks)} TASKS</span>${icon('arrow')}</footer></div></button>`;
  }
  function agentNetwork(agents,selected,view='graph',zoom=1){
    if(view==='list')return `<div class="network-list">${agents.map(a=>agentCard(a,a.id===selected,'compact')).join('')}</div>`;
    if(!agents.length)return empty('No active swarm','Connect the runtime to load your persistent profiles.');
    const sorted=[...agents].sort((a,b)=>(a.id==='admin'?-1:b.id==='admin'?1:0));
    const nodes=sorted.map((a,i)=>{if(!i)return {a,x:460,y:253};const angle=-Math.PI/2+(i-1)*2*Math.PI/(sorted.length-1);return {a,x:460+285*Math.cos(angle),y:253+178*Math.sin(angle)}});
    return `<div class="network-stage">${art('network-botanical')}<svg class="agent-network" viewBox="0 0 920 520" aria-label="Swarm coordination map"><defs>${nodes.map(({a},i)=>`<clipPath id="avatar-${i}"><circle cx="0" cy="0" r="${i?34:44}"/></clipPath>`).join('')}</defs><g transform="translate(${460*(1-zoom)} ${260*(1-zoom)}) scale(${zoom})"><g class="network-orbits"><ellipse cx="460" cy="253" rx="285" ry="178"/><ellipse cx="460" cy="253" rx="190" ry="119"/><path d="M100 253h720M460 22v462"/></g>${nodes.slice(1).map(({x,y})=>`<path class="network-edge" d="M460 253L${x} ${y}"/><circle class="edge-dot" cx="${460+(x-460)*.53}" cy="${253+(y-253)*.53}" r="3"/>`).join('')}${nodes.map(({a,x,y},i)=>`<g data-agent="${esc(a.id)}" role="button" tabindex="0" aria-label="Focus ${esc(a.name)}" class="network-node ${a.id===selected?'selected':''}" transform="translate(${x} ${y})"><circle class="node-halo" r="${i?42:52}"/><circle class="node-ring" r="${i?38:48}"/><image href="${portrait(a.id)}" x="-${i?34:44}" y="-${i?34:44}" width="${i?68:88}" height="${i?68:88}" preserveAspectRatio="xMidYMid slice" clip-path="url(#avatar-${i})"/><text class="node-name" y="${i?60:72}" text-anchor="middle">${esc(a.name)}</text><text class="node-status" y="${i?79:91}" text-anchor="middle">${esc(String(a.status).toUpperCase())}</text></g>`).join('')}</g><text class="graph-folio" x="22" y="473">DISTRIBUTED INTELLIGENCE</text><text class="graph-folio" x="22" y="490">SHARED CONTEXT / JEV</text><path class="graph-cross" d="M35 60h26M48 47v26M863 435h26M876 422v26"/></svg></div>`;
  }
  const sources=[['memories','Memories','memory'],['messages','Conversations','mail'],['tasks','Tasks','check'],['findings','Findings','search'],['decisions','Decisions','swarm'],['artifacts','Artifacts','file']];
  function memoryNetwork(counts,selected='',dark=false){
    const pts=sources.map((s,i)=>{const a=-Math.PI/2+i*2*Math.PI/6;return {s,x:300+192*Math.cos(a),y:253+178*Math.sin(a)}});
    return `<div class="memory-network ${dark?'dark':''}">${!dark?art('network-botanical'):''}<svg viewBox="0 0 600 530" aria-label="Workspace source map; lines represent categories, not inferred relationships"><g class="network-orbits"><circle cx="300" cy="253" r="178"/><circle cx="300" cy="253" r="116"/><path d="M54 253h492M300 22v478"/></g>${pts.map(({x,y})=>`<path class="network-edge" d="M300 253L${x} ${y}"/>`).join('')}<circle class="memory-center" cx="300" cy="253" r="49"/><g transform="translate(278 229) scale(1.1)"><path fill="currentColor" d="M4 39 16 5h9L13 39H4Zm18-25 14 25h-9l-9-17 4-8Z" class="memory-logo"/></g>${pts.map(({s,x,y})=>`<g data-source="${s[0]}" class="memory-source ${selected===s[0]?'selected':''}" role="button" tabindex="0" aria-label="View ${s[1]}"><circle class="source-halo" cx="${x}" cy="${y}" r="13"/><circle class="source-dot" cx="${x}" cy="${y}" r="8"/><text class="source-label" x="${x}" y="${y+30}" text-anchor="middle">${s[1]}</text><text class="source-count" x="${x}" y="${y+47}" text-anchor="middle">${num(counts[s[0]])} ITEMS</text></g>`).join('')}</svg><div class="graph-caption">${dark?'PERSISTENT CONTEXT':'WORKSPACE SOURCE MAP'}<span>${dark?'//':'Actual counts · category links'}</span></div></div>`;
  }
  Object.assign(U,{esc,PAGES,title,portrait,roleIcon,num,time,date,pill,status,button,miniButton,frame,empty,field,select,toggle,art,hero,shell,agentCard,agentNetwork,memoryNetwork,sources});
})();
