/* Frames are composed from shared DOM components; no screenshot is a UI control. */
(() => {
  'use strict';
  const U=window.EutryaUI, M=window.EutryaStudio;
  const {esc,icon,logo,portrait,floral,button,empty,status,panel,stamp,hero,agentCard,network,sourceGraph}=U;
  const {state,agents,selectedAgent,selectedProfile,profileDraft,ws,ready,mode,isPreview,config,events,availableTools,activeTasks,memory,records,groups,time,eventLabel}=M;
  const disabled=()=>state.connected?'':'disabled';
  const runtimeDisabled=()=>ready()?'':'disabled';
  const actionLink=(label,action,attrs='')=>button(label,action,'arrow','text',attrs);
  const kv = rows => `<dl class="kv">${rows.map(([a,b])=>`<dt>${esc(a)}</dt><dd>${esc(b)}</dd>`).join('')}</dl>`;
  const field=(label,name,value,type='text',hint='',attrs='')=>`<label class="form-field"><span>${esc(label)}</span><input data-config="${esc(name)}" id="setting-${esc(name)}" type="${type}" value="${esc(value??'')}" ${attrs}>${hint?`<small>${esc(hint)}</small>`:''}</label>`;
  const selectField=(label,name,value,options,attrs='')=>`<label class="form-field"><span>${esc(label)}</span><select id="setting-${esc(name)}" data-config="${esc(name)}" ${attrs}>${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
  const toggle=(label,name,checked,hint='',attrs='')=>`<label class="switch-field"><span>${esc(label)}<small>${esc(hint)}</small></span><input type="checkbox" role="switch" aria-label="${esc(label)}" data-config="${esc(name)}" ${checked?'checked':''} ${attrs}></label>`;
  function banner(){
    if(isPreview()) return `<aside class="notice preview"><div><strong>${mode()==='preview'?'UI preview · sample data, not your live workspace':'Demo runtime · no live model calls'}</strong></div>${button('Settings','navigate','settings','', 'data-page="settings"')}</aside>`;
    if(ready()) return '';
    const error=state.error||state.data?.readiness?.error||'Waiting for the local Eutrya runtime. No live work has started.';
    return `<aside class="notice"><div><strong>${state.connected?'Runtime setup required':mode()==='connecting'?'Connecting to runtime':'Runtime offline'}</strong><p>${esc(error)}</p></div>${button('Open settings','navigate','settings','primary','data-page="settings"')}</aside>`;
  }
  function activity(limit=7){const list=events().filter(e=>e.type!=='desktop.token').slice(-limit).reverse();return list.length?`<div class="activity-list">${list.map(e=>`<div class="activity-row"><time>${time(e.at)}</time><span>${esc(eventLabel(e))}</span></div>`).join('')}</div>`:empty('No runtime activity yet','Events appear here after the runtime reports them.');}
  function tasks(limit=5){const list=activeTasks().slice(0,limit);return list.length?list.map(t=>`<div class="task-row"><div><strong>${esc(t.title||'Untitled task')}</strong><small>${esc(t.assignedTo||'Unassigned')}</small></div>${status(String(t.status||'queued'),String(t.status)==='working'?'working':'waiting')}</div>`).join(''):empty('The queue is clear','Assign work through the agent conversation.');}
  function runtimeSummary(){const cfg=config();return `<div class="runtime-summary">${kv([['Runtime',state.connected?mode():'Offline'],['Provider',cfg.mainProvider||'Not configured'],['Model',cfg.mainModel||'Not configured']])}<div class="jev-label"><strong>Jev</strong><span>${cfg.jevCompaction?'COMPACTION ENABLED':'COMPACTION OFF'}<br>${ready()?'RUNTIME READY':'AWAITING RUNTIME'}</span></div></div>`;}
  function chat(){
    const target=selectedAgent();
    const messages=(ws().messages||[]).filter(m=>state.selectedAgent==='admin'||m.from===state.selectedAgent||m.to===state.selectedAgent||m.from==='user').slice(-40);
    const renderMessage=m=>{const mine=m.from==='user';const name=mine?'You':(agents().find(a=>a.id===m.from)?.name||m.from||'Eutrya');return `<div class="chat-message ${mine?'mine':''}"><div class="chat-avatar">${mine?'YOU':logo()}</div><div class="chat-body"><div class="chat-meta"><strong>${esc(name)}</strong><time>${time(m.timestamp||m.at)}</time></div><div class="chat-bubble">${esc(m.content||m.text||'')}</div></div></div>`;};
    const body=messages.length?messages.map(renderMessage).join(''):empty(ready()?'Ready when you are.':'Connect your runtime to begin.',ready()?`Talk to ${target.name} or let Admin coordinate the team.`:'Configure the local bridge and model provider in Settings.');
    return panel(`Chat // ${target.name}`,`<div class="chat-feed" data-scroll="chat">${body}${state.outbox?renderMessage({from:'user',content:state.outbox,at:Date.now()}):''}${state.chatBusy?`<div class="chat-message"><div class="chat-avatar">${logo()}</div><div class="chat-body"><div class="chat-bubble" role="status">Working… Waiting for the runtime response.</div></div></div>`:''}</div><div class="chat-commands">${button('/Reload','reload','','',runtimeDisabled())}${button('/Swarm','navigate','','','data-page="swarm"')}${button('/Memory','navigate','','','data-page="memory"')}${button('/Tools','navigate','','','data-page="tools"')}</div><form id="chat-form" class="chat-composer"><label class="sr-only" for="chat-draft">Message ${esc(target.name)}</label><textarea id="chat-draft" rows="2" placeholder="Message ${esc(target.name)}…" ${!ready()||state.chatBusy?'disabled':''}>${esc(state.chatDraft)}</textarea>${state.chatBusy?button('Stop','stop','stop','primary square','type="button" aria-label="Stop agent work"'):`<button class="btn primary square" type="submit" aria-label="Send message" ${runtimeDisabled()}>${icon('send')}</button>`}</form>`,'chat-panel',status(ready()?'Connected':'Not linked',ready()?'online':'offline'));
  }
  function dashboard(){
    const all=agents(), real=state.data?.swarm?.profiles||[];
    const toolCount=new Set(real.filter(a=>a.enabled!==false).flatMap(a=>a.tools||[])).size;
    const metric=`<div class="metric-strip"><div><strong>${state.connected?real.length:'—'}</strong><small>AGENTS</small></div><div><strong>${state.connected?toolCount:'—'}</strong><small>TOOLS</small></div><div><strong>${state.connected?memory().length:'—'}</strong><small>MEMORIES</small></div><div><strong>${state.connected?activeTasks().length:'—'}</strong><small>ACTIVE TASKS</small></div></div>`;
    return `${banner()}${hero('dashboard',metric)}<div class="dashboard-middle">${panel('Agents',`<div class="agent-strip">${all.slice(0,5).map(a=>agentCard(a,a.id===state.selectedAgent,'strip')).join('')}</div>`,'agents-panel',actionLink(`View all ${all.length}`,'navigate','data-page="swarm"'))}${panel('Runtime',runtimeSummary(),'system-panel',status(ready()?'Ready':'Not ready',ready()?'online':'offline'))}</div><div class="dashboard-bottom">${chat()}<div class="side-stack">${panel('Recent activity',activity(5),'',actionLink('See all','events'))}${panel('Current tasks',tasks(3),'',actionLink('Queue','navigate','data-page="swarm"'))}</div>${panel('Memory map',`${sourceGraph(groups(),'all',true)}<div class="memory-note">PERSISTENT CONTEXT<br>COMPOUNDING POSSIBILITIES</div>`,'dashboard-memory',actionLink('Open','navigate','data-page="memory"'))}</div>`;
  }
  function inspector(a){return panel('Agent inspector',`<div class="inspector-identity"><img src="${portrait(a.id)}" alt=""><div><h3>${esc(a.name)}</h3>${status(a.statusLabel,a.tone)}<p>${esc(a.role)}</p></div></div><p class="inspector-description">${esc(a.description)}</p><div class="inspector-section">${kv([['Agent ID',a.id],['Role',a.role],['Model',a.model||config().mainModel||'Not configured'],['Active tasks',a.taskCount],['Permissions',`${a.tools.length} assigned tools`]])}</div><div class="inspector-section"><h4>Capabilities</h4><div class="tags">${a.verbs.map(v=>`<span>${esc(v)}</span>`).join('')}</div></div><div class="inspector-section">${button('Open agent conversation','agent-chat','arrow','primary full',`data-id="${esc(a.id)}"`)}</div>`,'inspector',status(a.statusLabel,a.tone));}
  function swarm(){
    const all=agents(), a=selectedAgent();
    return `${banner()}${hero('swarm')}<div class="swarm-main">${panel('Swarm topology',network(all,state.selectedAgent,state.networkView),'',`<div class="button-row"><div class="segmented"><button class="${state.networkView==='graph'?'active':''}" data-action="network-view" data-view="graph" aria-label="Network view">${icon('swarm')}</button><button class="${state.networkView==='list'?'active':''}" data-action="network-view" data-view="list" aria-label="Agent list">${icon('list')}</button></div>${button('Add agent','add-agent','plus','',runtimeDisabled())}</div>`)}${inspector(a)}</div><div class="swarm-lower">${panel('Swarm activity',activity(5),'',status(ready()?'Live':'Offline',ready()?'online':'offline'))}${panel('Task queue',tasks(5),'',stamp(`${activeTasks().length} ACTIVE`))}${panel('Shared workspace',`<div class="pad">${kv([['Primary agent',state.data?.swarm?.matrix?.primaryAgent||'admin'],['Current template',state.data?.swarm?.matrix?.activeTemplate||'default'],['Blockers',(state.data?.swarm?.matrix?.blockers||[]).length],['Shared records',records().length]])}<div class="template-select">${['default','engineering','startup','legal','research'].map(t=>button(t,'template','','',`data-template="${t}" ${runtimeDisabled()}`)).join('')}</div><p class="read-only-note">Changing a template updates the runtime's agent configuration. Existing approval gates still apply.</p></div>`,'',stamp('CONTEXT / COORDINATION'))}</div>`;
  }
  function library(){
    const a=selectedProfile(), draft=profileDraft();
    const filtered=agents().filter(a=>`${a.name} ${a.role} ${a.description}`.toLowerCase().includes(state.agentQuery.toLowerCase()));
    const tabs=`<div class="section-tabs">${['configuration','capabilities'].map(t=>`<button data-action="profile-tab" data-tab="${t}" class="${state.profileTab===t?'active':''}">${t}</button>`).join('')}</div>`;
    const editor=state.profileTab==='capabilities'?`<div class="pad"><div class="tags">${a.tools.map(t=>`<span>${esc(t)}</span>`).join('')}</div><p class="read-only-note">Assigned tools are enforced by the runtime. Global write and execution policy is managed in Settings.</p>${button('Runtime permissions','navigate','lock','','data-page="settings"')}</div>`:`<div class="pad form-stack editor-fields"><label class="form-field"><span>Name</span><input id="profile-name" data-profile="name" value="${esc(draft.name)}" ${runtimeDisabled()}></label><label class="form-field"><span>Role</span><input id="profile-role" data-profile="role" value="${esc(draft.role)}" ${runtimeDisabled()}></label><label class="form-field"><span>Profession</span><input id="profile-profession" data-profile="profession" value="${esc(draft.profession)}" ${runtimeDisabled()}></label><label class="form-field"><span>Model override</span><input id="profile-model" data-profile="model" value="${esc(draft.model)}" placeholder="Use swarm default" ${runtimeDisabled()}></label><label class="form-field"><span>System instructions</span><textarea id="profile-instructions" data-profile="instructions" rows="7" ${runtimeDisabled()}>${esc(draft.instructions)}</textarea></label></div>`;
    return `${banner()}${hero('library')}<div class="toolbar"><label class="search-field">${icon('search')}<input id="agent-search" placeholder="Search agents, roles, capabilities…" value="${esc(state.agentQuery)}" aria-label="Search agents"></label><div class="segmented"><button data-action="library-view" data-view="grid" class="${state.libraryView==='grid'?'active':''}" aria-label="Grid view">${icon('grid')}</button><button data-action="library-view" data-view="list" class="${state.libraryView==='list'?'active':''}" aria-label="List view">${icon('list')}</button></div>${button('New agent','add-agent','plus','primary',runtimeDisabled())}</div><div class="library-layout">${panel('Agent profiles',`<div class="${state.libraryView==='grid'?'library-grid':'library-list'}">${filtered.map(p=>agentCard(p,p.id===a.id)).join('')||empty('No matching agents')}${state.libraryView==='grid'?`<button class="new-agent-card" data-action="add-agent" ${runtimeDisabled()}>${icon('plus')}<strong>CREATE NEW AGENT</strong><p>Customize a specialist for your workflow.</p></button>`:''}</div>`,'',stamp(`${filtered.length} PROFILES`))}${panel('Selected profile',`<div class="inspector-identity"><img src="${portrait(a.id)}" alt=""><div><h3>${esc(a.name)}</h3>${status(a.statusLabel,a.tone)}<p>${esc(a.role)}</p></div></div>${tabs}${editor}<div class="editor-actions">${button('Remove','remove-agent','trash','danger',`${a.id==='admin'||!ready()?'disabled':''}`)}${button('Save changes','save-profile','check','primary',runtimeDisabled())}</div>`,'profile-editor',stamp(state.profileDrafts[a.id]?'UNSAVED':'PROFILE'))}</div>`;
  }
  function memoryPage(){
    const all=records();const filtered=all.filter(r=>(state.source==='all'||r.source===state.source)&&`${r.title} ${r.text}`.toLowerCase().includes(state.memoryQuery.toLowerCase()));
    const selected=filtered.find(r=>r.key===state.selectedRecord)||filtered[0];
    const detail=selected?`<div class="detail-art">${floral()}<span>KNOWLEDGE<br>IN CONTEXT<br>// EUTRYA</span></div><div class="pad"><h3>${esc(selected.title)}</h3><div class="metadata"><span>${icon('file')}${esc(selected.source)}</span><span>${icon('clock')}${time(selected.time,true)}</span></div><p class="record-text">${esc(selected.text)}</p><div class="tags"><span>${esc(selected.author)}</span><span>${esc(selected.source)}</span></div></div><div class="pad button-row">${button('Copy text','copy-record','copy','',`data-id="${esc(selected.key)}"`)}${selected.deletable?button('Forget','forget','trash','danger',`data-id="${esc(selected.id)}" ${disabled()}`):''}</div>`:empty('No record selected','Add a memory or select a workspace record.');
    return `${banner()}${hero('memory')}<div class="memory-layout">${panel('Memory archive',`<label class="search-field">${icon('search')}<input id="memory-search" aria-label="Search memory" placeholder="Search your context…" value="${esc(state.memoryQuery)}"></label><div class="segmented">${[['all','All'],...groups().map(g=>[g.id,g.name])].map(([id,name])=>`<button data-action="memory-source" data-id="${id}" class="${state.source===id?'active':''}">${name}</button>`).join('')}</div><div class="record-list" data-scroll="records">${filtered.map(r=>`<button class="record-item ${r.key===selected?.key?'selected':''}" data-action="record" data-id="${esc(r.key)}">${icon('file')}<span><strong>${esc(r.title)}</strong><p>${esc(r.text.slice(0,120))}</p><small>${esc(r.source)} · ${time(r.time,true)}</small></span></button>`).join('')||empty('No matching records')}</div><div class="bottom-action">${button('New memory','add-memory','plus','primary full',disabled())}</div>`,'memory-archive',stamp(`${filtered.length} RECORDS`))}${panel('Context map',sourceGraph(groups(),state.source),'',stamp('SOURCE GROUPS'))}${panel('Selected memory',detail,'memory-detail',stamp(selected?.source||'READY'))}</div>`;
  }
  function tools(){
    const all=availableTools(), current=all.find(t=>t.name===state.selectedTool)||all[0];
    const filtered=all.filter(t=>(state.toolCategory==='all'||t.category===state.toolCategory)&&`${t.name} ${t.description}`.toLowerCase().includes(state.toolQuery.toLowerCase()));
    const cards=filtered.map(t=>`<button class="tool-card ${t.name===current.name?'selected':''}" data-action="tool" data-name="${esc(t.name)}">${floral()}<div class="tool-card-head"><span class="tool-icon">${icon(t.icon)}</span><div><h3>${esc(t.name)}</h3>${status(t.profiles.length?'Assigned':'Not assigned',t.profiles.length?'idle':'offline')}</div></div><p>${esc(t.description)}</p><small>${esc(t.category.toUpperCase())} / ${t.profiles.length} PROFILES</small></button>`).join('');
    const steps=[['file','Request'],['memory','Jev'],['lock','Decision gate'],['tools','Tool'],['file','Observation']];
    const log=events().filter(e=>e.type!=='desktop.token').slice(-12).map(e=>`${time(e.at)}  ${eventLabel(e)}`).join('\n');
    const details=`<div class="pad tool-info"><div class="tool-title"><span class="tool-icon">${icon(current.icon)}</span><div><h3>${esc(current.name)}</h3>${status(current.profiles.length?'Assigned':'Not assigned',current.profiles.length?'idle':'offline')}</div></div><p>${esc(current.description)}</p>${kv([['Category',current.category],['Assigned profiles',current.profiles.length],['Workspace writes',config().autoWrite?'Auto-approved':'Approval required'],['Local execution',config().allowExec?'Offered':'Disabled']])}<div class="inspector-section"><h4>Runtime tools</h4><div class="tags">${current.keys.map(k=>`<span>${esc(k)}</span>`).join('')}</div></div><div class="inspector-section"><h4>Used by</h4><div class="tags">${current.profiles.map(p=>`<span>${esc(p.name)}</span>`).join('')||'<span>No assigned profiles</span>'}</div></div><p class="read-only-note">Tools run through agent requests and the existing permission gate. This screen does not bypass approvals.</p>${button('Configure permissions','navigate','lock','primary full','data-page="settings"')}</div>`;
    return `${banner()}${hero('tools')}<div class="toolbar"><div class="segmented">${['all','Data','Research','Execution','Collaboration'].map(c=>`<button class="${state.toolCategory===c?'active':''}" data-action="tool-category" data-category="${c}">${c==='all'?'All tools':c}</button>`).join('')}</div><label class="search-field">${icon('search')}<input id="tool-search" aria-label="Search tools" placeholder="Search tools…" value="${esc(state.toolQuery)}"></label></div><div class="tools-layout"><div class="tool-main-stack">${panel('Tool library',`<div class="tool-grid">${cards||empty('No matching tools')}</div>`,'',stamp('PROFILE PERMISSIONS'))}${panel('Runtime path',`<div class="pipeline">${steps.map(([i,n],ix)=>`<div class="pipeline-step">${icon(i)}${n}</div>${ix<steps.length-1?icon('arrow'):''}`).join('')}</div>`,'',stamp('ARCHITECTURE'))}${panel('Execution console',`<pre class="console" data-scroll="console">${esc(log||'Waiting for runtime events. No tools have been executed in this view.')}</pre>`,'',actionLink('All events','events'))}</div>${panel('Tool details',details,'',stamp('RUNTIME CONTROLLED'))}</div>`;
  }
  function settings(){
    const cfg=config(), draft=state.configDraft||cfg, native=Boolean(window.__TAURI__), categories=[['all','All settings'],['models','Models'],['providers','Providers'],['runtime','Runtime'],['permissions','Permissions'],['workspace','Workspace'],['appearance','Appearance']];
    const card=(key,title,body,aside='')=>panel(title,body,`settings-card setting-group ${state.settingsTab!=='all'&&state.settingsTab!==key?'hidden':''}`,aside);
    const models=card('models','Model configuration',`<p class="settings-intro">Choose the text model and evaluator used by your native swarm.</p><div class="form-stack">${selectField('Main provider','mainProvider',draft.mainProvider||'vercel',[['vercel','Vercel AI Gateway'],['chatgpt','ChatGPT adapter'],['openrouter','OpenRouter'],['compatible','OpenAI-compatible'],['ollama','Ollama']],disabled())}${field('Model identifier','mainModel',draft.mainModel,'text','Use the model ID accepted by your configured provider.',disabled())}<label class="form-field"><span>Jev evaluator</span><input value="${esc(cfg.jevModel||'Not configured')}" readonly><small>Evaluator selection is controlled by the runtime configuration.</small></label></div>`,icon('memory'));
    const providers=card('providers','Provider credentials',`<p class="settings-intro">Keys are passed to the existing local credential store. Saved keys are never read back into these fields.</p><div class="provider-card active"><span class="provider-mark">V</span><span><strong>Jev / Vercel</strong><small>AI_GATEWAY_API_KEY</small></span>${status(cfg.jevKeyPresent?'Present':'Missing',cfg.jevKeyPresent?'idle':'offline')}</div><form id="jev-key-form" class="form-stack"><label class="form-field"><span>Replace gateway key</span><input id="jev-key" type="password" autocomplete="new-password" placeholder="Enter a new key" ${disabled()}></label><button type="submit" class="btn" ${disabled()}>Save gateway key</button></form>${cfg.mainKeyEnv&&cfg.mainKeyEnv!=='AI_GATEWAY_API_KEY'?`<div class="inspector-section"><div class="provider-card"><span class="provider-mark">${esc((cfg.mainProvider||'P')[0].toUpperCase())}</span><span><strong>${esc(cfg.mainProvider)}</strong><small>${esc(cfg.mainKeyEnv)}</small></span>${status(cfg.mainKeyPresent?'Present':'Missing',cfg.mainKeyPresent?'idle':'offline')}</div><form id="provider-key-form" class="form-stack"><label class="form-field"><span>Replace provider key</span><input id="provider-key" type="password" autocomplete="new-password" placeholder="Enter a new key" ${disabled()}></label><button type="submit" class="btn" ${disabled()}>Save provider key</button></form></div>`:''}<p class="read-only-note">Changing provider? Apply your model settings first, then save that provider's credential.</p>`,icon('lock'));
    const runtime=card('runtime','Execution limits',`<p class="settings-intro">Budgets apply to the runtime, not just the display.</p><div class="form-columns">${field('Max steps','maxSteps',draft.maxSteps??24,'number','',`min="1" max="500" ${disabled()}`)}${field('Max calls','maxCalls',draft.maxCalls??150,'number','',`min="1" max="10000" ${disabled()}`)}${field('Output tokens','maxOutputTokens',draft.maxOutputTokens??6144,'number','',`min="256" max="64000" ${disabled()}`)}${field('Timeout (ms)','timeoutMs',draft.timeoutMs??90000,'number','',`min="100" max="600000" ${disabled()}`)}</div>`,icon('terminal'));
    const permissions=card('permissions','Permissions & memory',`${toggle('Auto-approve workspace writes','autoWrite',draft.autoWrite,'Allow writes without an individual approval prompt.',disabled())}${toggle('Offer local process execution','allowExec',draft.allowExec,'Expose process tools to agents; runtime gates remain authoritative.',disabled())}${toggle('Jev compaction','jevCompaction',draft.jevCompaction,'Use the runtime’s Jev context-compaction layer.',disabled())}<p class="read-only-note">Only enable permissions you intend to grant. The interface does not execute tools outside the runtime.</p>`,icon('lock'));
    const workspaceCard=card('workspace','Workspace',`<p class="settings-intro">A local directory shared with your native runtime.</p><label class="form-field"><span>Active workspace</span><input id="workspace-path" value="${esc(cfg.workspace||window.EutryaBackend?.info?.workspace||'')}" ${!native?'disabled':''}></label><div class="button-row" style="margin-top:12px">${button('Switch workspace','workspace','folder','',!native?'disabled':'')}</div><div class="inspector-section">${kv([['Config file',cfg.configFile||'Unavailable'],['Memory location',cfg.dataRoot||'Unavailable']])}</div>${!native?'<p class="read-only-note">Workspace switching is available in the Tauri desktop app.</p>':''}`,icon('folder'));
    const appearance=card('appearance','Interface',`<p class="settings-intro">Presentation-only preferences. Stored locally, never sent as model configuration.</p><label class="form-field"><span>Density</span><select id="ui-density"><option value="precise" ${state.preferences.density==='precise'?'selected':''}>Precise · reference layout</option><option value="comfortable" ${state.preferences.density==='comfortable'?'selected':''}>Comfortable · more spacing</option></select></label><label class="switch-field"><span>Reduce interface motion<small>Keep transitions still.</small></span><input type="checkbox" role="switch" id="ui-motion" aria-label="Reduce interface motion" ${state.preferences.motion==='off'?'checked':''}></label>`,icon('dashboard'));
    const runtimeStatus=card('runtime','Runtime status',`<div class="runtime-status-card">${status(ready()?'Runtime ready':state.connected?'Setup required':'Not connected',ready()?'online':'offline')}<div style="margin-top:16px">${kv([['Mode',mode()],['Node',state.data?.readiness?.node||'Unavailable'],['Bridge',state.data?.readiness?.bridgeVersion||'Unavailable'],['Agent profiles',state.data?.swarm?.profiles?.length??'Unavailable']])}</div>${state.error||state.data?.readiness?.error?`<p class="runtime-error">${esc(state.error||state.data.readiness.error)}</p>`:''}${button('Reconnect','reconnect','reload','',state.pending.has('reconnect')?'disabled':'')}${button('Restart bridge','restart','reload','',!native?'disabled':'')}</div>`,icon('info'));
    return `${banner()}${hero('settings')}<div class="toolbar"><div class="segmented">${categories.map(([id,name])=>`<button data-action="settings-tab" data-tab="${id}" class="${state.settingsTab===id?'active':''}">${name}</button>`).join('')}</div></div><div class="settings-grid ${state.settingsTab!=='all'?'filtered':''}"><div class="settings-column">${models}${runtime}${appearance}</div><div class="settings-column">${providers}${permissions}</div><div class="settings-column">${workspaceCard}${runtimeStatus}</div></div><div class="settings-actions"><span class="${state.configDirty?'unsaved':''}">${state.configDirty?'Unsaved runtime changes':'Runtime settings match the last received snapshot'}</span><div class="button-row">${button('Discard changes','discard-config','','',!state.configDirty?'disabled':'')}${button('Apply runtime settings','save-config','check','primary',!state.configDirty||!state.connected?'disabled':'')}</div></div>`;
  }
  function shell(){return `<div class="app-shell"><header class="titlebar" id="titlebar"><div class="window-lights" aria-hidden="true"><i></i><i></i><i></i></div><span class="titlebar-wordmark">// ORCHESTRATE HIGHER INTELLIGENCE</span><div class="titlebar-state" id="connection-status"></div><div class="window-controls">${button('Minimize','window-min','minus','square','aria-label="Minimize window"')}${button('Maximize','window-max','maximize','square','aria-label="Maximize window"')}${button('Close','window-close','close','square','aria-label="Close window"')}</div></header><aside class="sidebar"><div class="brand-lockup">${logo()}<div><div class="brand-name">Eutrya</div><div class="brand-version">v0.2.0 / STUDIO</div></div></div><nav class="primary-nav" aria-label="Main navigation">${M.names.map(p=>`<button class="nav-item" data-action="navigate" data-page="${p}" aria-label="${p[0].toUpperCase()+p.slice(1)}" title="${p[0].toUpperCase()+p.slice(1)}">${icon(p)}<span>${p[0].toUpperCase()+p.slice(1)}</span></button>`).join('')}</nav><div class="sidebar-art" aria-hidden="true"></div><div class="sidebar-footer"><strong>HUMAN<br>AI<br>HIGHER INTELLIGENCE</strong>// eutrya<br>BUILT FOR THE LONG RUN</div></aside><main id="workspace" class="workspace"><div class="page" id="page"></div></main></div><dialog id="modal" aria-labelledby="modal-title"></dialog><div id="toast" class="toast hidden" role="status" aria-live="polite"></div>`;}
  const pages={dashboard,swarm,library,memory:memoryPage,tools,settings};
  function renderPage(){return `${pages[state.page]()}<footer class="page-footer"><span>EUTRYA / ${esc(state.page.toUpperCase())} / STUDIO 03</span><span>${state.connected?'BRIDGE LINKED':'BRIDGE NOT LINKED'} · ${esc(mode().toUpperCase())}</span></footer>`;}
  window.EutryaViews={shell,renderPage,activity,banner};
})();
